### ISSUE TITLE
[css-text] Clarify whether soft breaks exist at boundaries of an inline element with `word-break:break-all`

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#103]
Resolutions were made for [csswg-drafts/#3897](https://github.com/w3c/csswg-drafts/issues/3897).

**\[css\-text\] Clarify whether soft breaks exist at boundaries of an inline element with \`word\-break:break\-all\`**

* RESOLVED: It's undefined
* RESOLVED: i.e., the presence of soft break opportunities between spans which change soft breaking opportunities is undefined

[Discussion.](https://github.com/w3c/csswg-drafts/issues/3897#issuecomment-532057510)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by heycam** [comment]
This was resolved to be explicitly undefined. @jfkthame I'm not sure if you wanted to go ahead with the change in behavior you mentioned in https://github.com/w3c/csswg-drafts/issues/3897#issue-441340595 or to leave our current behavior as is.  (I just noticed your link to the issue while reading through nsLineBreaker.h.)

**Comment by jfkthame** [comment]
As of bug 1549728, we do implement that behavior, as shown by an example like

     data:text/html,<div style="width:0">abc<span style="word-break:break-all">xyz</span>def

which Firefox renders as

    abc
    x
    y
    x
    def

(see https://bugzilla.mozilla.org/show_bug.cgi?id=1549728#c3). I currently get different results in Safari:

    abc
    x
    y
    zdef

and in Chrome:

    abcx
    y
    z
    def

The lack of interop is troubling, obviously, but the WG wasn't ready to reach a firm conclusion, so for the time being there's nothing to do here.

(Personally, I still think our current behavior makes more sense than either the Safari or Chrome results. Interestingly, the latter appears to have changed since https://github.com/w3c/csswg-drafts/issues/3897 was filed and is now asymmetrical -- but in the opposite way to Safari.)
