### ISSUE TITLE
[css-transforms] Zero value in perspective() function

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#121]
A resolution was made for [csswg-drafts/#413](https://github.com/w3c/csswg-drafts/issues/413).

**\[css\-transforms\] Zero value in perspective\(\) function**

* RESOLVED: 0 is allowed with 1px being the render time clamp

[Discussion.](https://github.com/w3c/csswg-drafts/issues/413#issuecomment-540477441)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
I think this needs a bug. Adding the `bug` label.

(As noted in https://github.com/w3c/csswg-drafts/issues/413 , we already had a Firefox bug filed on related stuff, https://bugzilla.mozilla.org/show_bug.cgi?id=1316236 -- but this CSSWG resolution from October 2019 requires a different behavior -- clamping small values to 1px, rather than having a discontinuity at 0 where we jump to infinity.)

I'm not sure if our implementation matches the requirement of "1px being the render time clamp", though. @upsuper do you happen to know?

**Comment by mozilla-apprentice** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1630441

**Comment by dholbert** [comment]
> I'm not sure if our implementation matches the requirement of "1px being the render time clamp", though. @upsuper do you happen to know?

Sorry, I initially typed this ^^ up and then meant to delete it after doing some investigation.  I'm pretty sure we *don't* do that render-time clamp, hence the new bug.  (Apologies for the spurious github-ping, @upsuper. Though: I'm happy to have you weigh in here or on the bug if you've got any additional thoughts/nuance. :) )
