### ISSUE TITLE
[css-text-decor] Limits on text-underline-offset to preserve semantic meaning

### ISSUE THREAD

**Issue by mozilla-apprentice** [mozilla/wg-decisions#78]
A resolution was made for [csswg-drafts/#4059](https://github.com/w3c/csswg-drafts/issues/4059).

**\[css\-text\-decor\] Limits on text\-underline\-offset to preserve semantic meaning**

* RESOLVED: always draw the underline even if it's spec to be outside a limit we choose

[Discussion.](https://github.com/w3c/csswg-drafts/issues/4059#issuecomment-512378640)

----

To file a bug automatically for these resolutions, add the **bug** label to the issue.

If no bug is needed, the issue can be closed.

**Comment by dholbert** [comment]
CC @charliemarlow

**Comment by dholbert** [comment]
If I understand the discussion, the resolution was just saying that:
 - there's still no resolution on whether or not we'll clamp the value (I think)
 - However: if the spec does end up requiring a clamp on the value, then the line would simply draw **at that clamped position** rather than being clipped.

A relevant quote from just before the resolution:
> <dael> astearns: jensimmons question is if we do agree on a limit do we agree underline will be drawn at that limit if author spec something outside limit.

And I think the resolution is just the CSSWG saying "yes" to this ^^ question.

**Comment by dholbert** [comment]
So for now, I don't think any bug/implementation change is required.  This resolution just informs what the implementation will look like, **if & when** the spec changes to require a clamp.
